sudo: required
dist: xenial

addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chefdk
      - docker-ce

services: docker

install: CHEF_LICENSE="accept" chef exec bundle

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"
  - docker --version

script:
  - chef exec berks
  - chef exec rspec
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify
